// <auto-generated />
using CCJShop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CCJShop.Migrations
{
    [DbContext(typeof(ParamContext))]
    [Migration("20210521074825_InitParam")]
    partial class InitParam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CCJShop.Models.Param", b =>
                {
                    b.Property<int>("ParamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpParamId")
                        .HasColumnType("int");

                    b.HasKey("ParamId");

                    b.ToTable("Param");

                    b.HasData(
                        new
                        {
                            ParamId = 1,
                            Code = "1",
                            GroupId = 1,
                            Memo = "地區",
                            Name = "北部",
                            UpParamId = 0
                        },
                        new
                        {
                            ParamId = 2,
                            Code = "2",
                            GroupId = 1,
                            Memo = "地區",
                            Name = "中部",
                            UpParamId = 0
                        },
                        new
                        {
                            ParamId = 3,
                            Code = "3",
                            GroupId = 1,
                            Memo = "地區",
                            Name = "南部",
                            UpParamId = 0
                        },
                        new
                        {
                            ParamId = 4,
                            Code = "4",
                            GroupId = 1,
                            Memo = "地區",
                            Name = "東部",
                            UpParamId = 0
                        },
                        new
                        {
                            ParamId = 5,
                            Code = "5",
                            GroupId = 1,
                            Memo = "地區",
                            Name = "外島",
                            UpParamId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
