// <auto-generated />
using System;
using CCJShop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CCJShop.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210521081209_AddDataProduct")]
    partial class AddDataProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CCJShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Memo = "內搭竹節T真的很好穿！\n忽冷忽熱的時候都可以搭配到 非常親膚\n整套搭配Claire自留\n渲染洋裝多層次穿搭百摺裙 讓整體更有變化\n比較偏一點點日系的搭配法\n洋裝不能調肩帶唷！\n但是材質有彈性 穿起來一樣親膚不刺癢",
                            Name = "個性渲染絲絨連身裙",
                            Price = 560,
                            Status = 1
                        });
                });

            modelBuilder.Entity("CCJShop.Models.ProductColor", b =>
                {
                    b.Property<int>("ProductColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductColorId");

                    b.ToTable("ProductColor");
                });

            modelBuilder.Entity("CCJShop.Models.ProductImg", b =>
                {
                    b.Property<int>("ProductImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImgId");

                    b.ToTable("ProductImg");

                    b.HasData(
                        new
                        {
                            ProductImgId = 1,
                            CDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgSrc = "https://instagram.ftpe5-1.fna.fbcdn.net/v/t51.2885-15/e35/s1080x1080/174079068_950674635472462_4447592011368211239_n.jpg?tp=1&_nc_ht=instagram.ftpe5-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=hmylVF-ezWkAX-Sk9pn&edm=AP_V10EBAAAA&ccb=7-4&oh=79e65203173c8f86022353da81649786&oe=60AF244D&_nc_sid=4f375e",
                            MDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductColorId = 0,
                            ProductId = 1
                        },
                        new
                        {
                            ProductImgId = 2,
                            CDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgSrc = "https://instagram.ftpe5-1.fna.fbcdn.net/v/t51.2885-15/e35/s1080x1080/173084051_1409041302766659_8619673499345077503_n.jpg?tp=1&_nc_ht=instagram.ftpe5-1.fna.fbcdn.net&_nc_cat=103&_nc_ohc=XEhZLjPa1wIAX9GpbeC&edm=AP_V10EBAAAA&ccb=7-4&oh=e8bb670a2aa5beda5e5fc0e3f1bf8e1b&oe=60AF0252&_nc_sid=4f375e",
                            MDT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductColorId = 0,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("CCJShop.Models.ProductSize", b =>
                {
                    b.Property<int>("ProductSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SizeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductSizeId");

                    b.ToTable("ProductSize");
                });
#pragma warning restore 612, 618
        }
    }
}
